name: MessageChannel
version: ${project.version}
description: ${project.description}
main: me.crypnotic.messagechannel.bukkit.MessageChannelBukkit
author: Crypnotic
api-version: 1.13
softdepend:
- CommandAPI